### ISSUE TITLE
NDEF read from NTAG 424?

### ISSUE THREAD

**Issue by FerGT50** [Obsttube/MFRC522_NTAG424DNA#1]
Hello,
is reading a full NDEF supported? I work with NTAG 424 DNA labels.
Using an ESP32 by the way, so no problems with firmware size or RAM usage.
Thanks

**Comment by Obsttube** [comment]
Hi, thanks for reaching out!

Reading a full NDEF is indeed supported. If you are using MFRC522 and want to read more than 59 bytes (in case of non-encrypted communication), then the protected function "DNA_ReadData_native" is called many times, but it shouldn't be a problem.

Just use "DNA_Plain_ReadData" for non-encrypted (plain) communication mode and read as many bytes as you want.

See the example at https://github.com/Obsttube/MFRC522_NTAG424DNA/blob/main/examples/Plain_ReadData/Plain_ReadData.ino which reads a whole 256 bytes long NDEF file.

It should work with ESP32, but I didn't test it on ESP32.

If you have further questions, don't hesitate to ask.

**Comment by FerGT50** [comment]
Works, many thanks!
