### ISSUE TITLE
Cant completely change sector 0

### ISSUE THREAD

**Issue by flakiwav** [Obsttube/MFRC522_NTAG424DNA#4]
Hello! I need to rewrite sector 0 completely (all 16 bytes). I'm using the "Change UID" example for this, changing the NEW_UID in it to the one I need. I also change the length to 16 in MIFARE_SetUid. I get the error "New UID buffer empty, size 0, or size > 15 given". Accordingly, I managed to rewrite only the first 15 bytes. How can I overwrite all 16 bytes of sector 0? Thanks!

**Comment by Obsttube** [comment]
Dear @flakiwav,

There is no such example as "Change UID". Please take a look: https://github.com/Obsttube/MFRC522_NTAG424DNA/tree/main/examples

Are you sure you are talking about a example from my library?

**Comment by flakiwav** [comment]
Oh, I'm sorry. Yes, I got the libraries mixed up.
